# Generated by Django 3.2.7 on 2021-09-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.newsmodel'),
        ),
    ]
